//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance
{
    using System;
    using System.Collections.Generic;
    
    public partial class C7Balance
    {
        public int BalanceID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Balance { get; set; }
    
        public virtual C7User C7User { get; set; }
    }
}
