//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance
{
    using System;
    using System.Collections.Generic;
    
    public partial class C7Tranzakcii
    {
        public int TranzakciiID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Summa { get; set; }
    
        public virtual C7KategoriPengeluaran C7KategoriPengeluaran { get; set; }
        public virtual C7User C7User { get; set; }
    }
}
